### ISSUE TITLE
Add rewrite notice to README

### ISSUE THREAD

**Issue by flokosiol** [pedroborges/kirby-asset-cachebuster#1]
Hey Pedro,

Really nice plugin, great work! 

I would recommend to add a notice to the `README` that it's necessary to modify the `.htaccess` file to make the plugin work (just like the [original cachebuster plugin](https://github.com/getkirby-plugins/cachebuster-plugin#htaccess-rules-for-apache) does).

**Comment by pedroborges** [comment]
Done. Thank you!
