### ISSUE TITLE
String issue

### ISSUE THREAD

**Issue by illycz** [pedroborges/kirby-asset-cachebuster#3]
I'm getting ```Argument 1 passed to asset() must be an instance of string```.
I'm using `<img src="<?= asset('image.jpg') ?>">` so I don't understand where is the problem :(

**Comment by pedroborges** [comment]
What's your PHP version?

**Comment by illycz** [comment]
5.6.31

**Comment by pedroborges** [comment]
Primitive type-hinting was only introduced in PHP 7.1. I just changed to be compatible with PHP 5.6.

Anyway, I recommend you to upgrade it since the latest PHP versions came with great performance improvements.
